CPPFLAGS += -g -I../../../common -std=c++11
PROBLEMS := p_2_4 p_2_5 p_2_6 p_2_7 p_3_1 p_3_2 p_3_8 p_3_7 p_4_1 p_4_2 p_4_3 p_4_4 p_4_5 p_4_6 p_4_7 p_5_1 p_5_2 p_5_3 p_5_6 p_5_7

all: $(PROBLEMS)

clean:
	rm -rf $(PROBLEMS) *.dSYM *.log
